-- ============================================================
-- Aggiunge la tabella "notifiche_inviate": registra ogni avviso
-- mandato a un giocatore quando il suo certificato medico viene
-- approvato o scartato (serve per non perdere lo storico, ed evitare
-- in futuro di mandare due volte lo stesso avviso).
--
-- IMPORTANTE (da sapere prima di eseguirlo): questa tabella tiene
-- traccia che "un avviso è stato generato", ma il sito NON manda
-- ancora email vere a nessuno — non abbiamo un servizio di posta
-- collegato. Il server, da quando aggiorni anche server.js con
-- questo aggiornamento, scriverà comunque una riga qui ogni volta
-- che un certificato viene approvato o scartato dalla pagina
-- "Approvazione", con l'email del giocatore interessato: è il primo
-- passo per un sistema di avvisi reali, che potremo collegare a un
-- servizio di posta in un secondo momento se vuoi.
--
-- Come usarlo: uguale agli altri script — SQL Editor su
-- supabase.com, incolla, Run.
-- ============================================================

create table if not exists notifiche_inviate (
  id bigint generated by default as identity primary key,
  id_certificato bigint not null references certificati_medici(id) on delete cascade,
  data_invio timestamptz not null default now(),
  destinatario text
);
