-- ============================================================
-- Aggiunge la tabella "segnalazioni_certificati": tiene traccia di
-- quando qualcuno carica un certificato medico scrivendo un nome che
-- non corrisponde a nessun giocatore del sito (prima veniva solo
-- mandata un'email all'Admin, senza salvare nulla nel database).
--
-- Con questa tabella, queste segnalazioni si possono gestire
-- direttamente dal sito, nella pagina Certificati medici >
-- Segnalazioni: l'Admin vede la foto e i dati scritti, e può
-- collegare la segnalazione a un giocatore vero (diventa un
-- certificato vero e proprio, da approvare o scartare come al
-- solito) oppure scartarla direttamente. La stessa pagina mostra
-- anche lo storico di tutte le segnalazioni ricevute finora.
--
-- Come usarlo:
-- 1. Apri il progetto su supabase.com
-- 2. Nel menu a sinistra vai su "SQL Editor"
-- 3. Clicca "New query"
-- 4. Incolla tutto questo file
-- 5. Clicca "Run" (o il pulsante Play)
--
-- Si può eseguire più di una volta senza rompere nulla.
-- ============================================================

create table if not exists segnalazioni_certificati (
  id bigint generated by default as identity primary key,

  -- Nome e cognome scritti da chi ha caricato il certificato (non è
  -- detto che corrispondano a un giocatore vero: è proprio per questo
  -- che la segnalazione esiste).
  nome text not null,
  cognome text not null,

  data_rilascio date not null,
  nota text,

  -- Percorso della foto nello Storage di Supabase (stesso "bucket" dei
  -- certificati veri, cartella "segnalazioni/").
  foto_path text not null,

  -- 'in_attesa': ancora da gestire (è quello che compare nella pagina
  --   "Da gestire").
  -- 'collegata': l'Admin l'ha collegata a un giocatore vero: è
  --   diventata un certificato vero e proprio (vedi id_certificato_creato).
  -- 'scartata': l'Admin l'ha scartata, non corrispondeva a nessuno.
  stato text not null default 'in_attesa' check (stato in ('in_attesa', 'collegata', 'scartata')),

  -- Compilati solo quando la segnalazione viene collegata a un
  -- giocatore vero.
  id_giocatore_collegato bigint references giocatori(id),
  id_certificato_creato bigint references certificati_medici(id),

  creato_il timestamptz not null default now(),
  gestito_il timestamptz
);
