-- ============================================================
-- Aggiunge la tabella "squadre" e collega ogni giocatore e ogni
-- responsabile (allenatore/staff) alla squadra a cui appartiene.
--
-- Come usarlo:
-- 1. Apri il progetto su supabase.com
-- 2. Nel menu a sinistra vai su "SQL Editor"
-- 3. Clicca "New query"
-- 4. Incolla tutto questo file
-- 5. Clicca "Run" (o il pulsante Play)
--
-- Si può eseguire più di una volta senza rompere nulla: gli "if
-- not exists" evitano errori se una parte è già stata creata.
-- ============================================================

-- 1) Nuova tabella con le squadre/categorie della società.
--    Le ho popolate con le stesse categorie già usate nel sito
--    (pagina Squadre): puoi rinominarle o aggiungerne altre in
--    qualsiasi momento dal Table Editor.
create table if not exists squadre (
  id bigint generated by default as identity primary key,
  nome text not null unique
);

insert into squadre (nome) values
  ('Prima Squadra'),
  ('Juniores'),
  ('Allievi'),
  ('Giovanissimi'),
  ('Esordienti'),
  ('Pulcini'),
  ('Primi Calci'),
  ('Scuola Calcio')
on conflict (nome) do nothing;

-- 2) Ogni giocatore appartiene a una squadra.
alter table giocatori add column if not exists id_squadra bigint references squadre(id);

-- I giocatori già presenti (dati di prova) vengono assegnati a
-- "Prima Squadra" in attesa di essere sistemati uno per uno dal
-- Table Editor.
update giocatori set id_squadra = (select id from squadre where nome = 'Prima Squadra')
where id_squadra is null;

-- Da qui in avanti il campo è obbligatorio: non si potrà più
-- salvare un giocatore senza squadra.
alter table giocatori alter column id_squadra set not null;

-- 3) Ogni responsabile (allenatore/staff) allena una squadra.
alter table responsabili add column if not exists id_squadra bigint references squadre(id);

update responsabili set id_squadra = (select id from squadre where nome = 'Prima Squadra')
where id_squadra is null;

alter table responsabili alter column id_squadra set not null;
