-- ============================================================
-- Aggiunge la tabella "certificati_medici": un certificato per
-- ogni giocatore (stato, foto, date), usata dalla pagina
-- "Certificati medici" del sito (Carica certificato / Approvazione).
--
-- Come usarlo:
-- 1. Apri il progetto su supabase.com
-- 2. Nel menu a sinistra vai su "SQL Editor"
-- 3. Clicca "New query"
-- 4. Incolla tutto questo file
-- 5. Clicca "Run" (o il pulsante Play)
--
-- Si può eseguire più di una volta senza rompere nulla: gli "if
-- not exists" evitano errori se è già stata creata.
--
-- Nota: lo spazio di archiviazione per le foto (lo "Storage bucket")
-- viene creato automaticamente dal server la prima volta che lo
-- avvii dopo questo aggiornamento: non serve fare nulla a mano su
-- Supabase per quello.
-- ============================================================

create table if not exists certificati_medici (
  id bigint generated by default as identity primary key,

  -- Un solo certificato "attivo" per giocatore: caricandone uno
  -- nuovo si sostituisce quello precedente (invece di accumulare
  -- uno storico). Se in futuro serve tenere lo storico, si può
  -- togliere "unique" e cambiare la logica del server.
  id_giocatore bigint not null unique references giocatori(id) on delete cascade,

  -- 'attesa'    = caricato, in attesa di approvazione
  -- 'approvato' = approvato dal responsabile
  stato text not null default 'attesa' check (stato in ('attesa', 'approvato')),

  -- percorso del file dentro lo Storage di Supabase (non l'immagine
  -- vera e propria: quella resta nello Storage, qui teniamo solo
  -- "dove trovarla")
  foto_path text,

  data_caricamento timestamptz not null default now(),
  data_approvazione timestamptz
);
