-- ============================================================
-- Permette a un giocatore di appartenere a PIÙ squadre insieme
-- (prima poteva stare in una sola squadra alla volta).
--
-- Come funzionava prima: ogni giocatore aveva una colonna
-- "id_squadra" che puntava a UNA sola squadra. Da qui in avanti,
-- invece, uso una tabella nuova ("giocatori_squadre") con una riga
-- per ogni collegamento giocatore-squadra: un giocatore può avere
-- tante righe quante sono le squadre a cui appartiene.
--
-- Questo script:
-- 1. crea la nuova tabella "giocatori_squadre";
-- 2. porta dentro la tabella nuova tutti i collegamenti già esistenti
--    (nessun giocatore perde la squadra che aveva);
-- 3. toglie la vecchia colonna "id_squadra" da "giocatori", che da
--    questo momento non serve più (il sito è stato aggiornato per
--    usare solo la tabella nuova).
--
-- IMPORTANTE: esegui questo script SOLO DOPO aver aggiornato anche
-- server.js e index.html con l'ultima versione che ti ho mandato:
-- se lo esegui prima, il sito smette di funzionare finché non
-- aggiorni anche quei due file (la vecchia versione del sito si
-- aspetta ancora la colonna "id_squadra").
--
-- Come usarlo:
-- 1. Apri il progetto su supabase.com
-- 2. Nel menu a sinistra vai su "SQL Editor"
-- 3. Clicca "New query"
-- 4. Incolla tutto questo file
-- 5. Clicca "Run" (o il pulsante Play)
--
-- Si può eseguire più di una volta senza rompere nulla (gli "if not
-- exists" e "on conflict" evitano errori se una parte è già stata
-- fatta), TRANNE l'ultimo pezzo che toglie la colonna "id_squadra":
-- una volta tolta, non c'è più nulla da togliere, ma non succede
-- nulla di male a rieseguire lo script.
-- ============================================================

-- 1) Nuova tabella: una riga per ogni "giocatore appartiene a questa
--    squadra". "on delete cascade" su entrambe le colonne vuol dire
--    che se elimini un giocatore o una squadra, i collegamenti che lo
--    riguardano spariscono da soli, senza lasciare righe orfane.
create table if not exists giocatori_squadre (
  id bigint generated by default as identity primary key,
  id_giocatore bigint not null references giocatori(id) on delete cascade,
  id_squadra bigint not null references squadre(id) on delete cascade,
  unique (id_giocatore, id_squadra)
);

-- 2) Porto dentro la tabella nuova la squadra che ogni giocatore aveva
--    già (solo se la colonna "id_squadra" esiste ancora: se lo script
--    è già stato eseguito una volta, questo pezzo non fa nulla).
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'giocatori' and column_name = 'id_squadra'
  ) then
    insert into giocatori_squadre (id_giocatore, id_squadra)
    select id, id_squadra from giocatori where id_squadra is not null
    on conflict (id_giocatore, id_squadra) do nothing;
  end if;
end $$;

-- 3) Tolgo la vecchia colonna "id_squadra" da "giocatori": da questo
--    momento le squadre di un giocatore si leggono solo dalla tabella
--    "giocatori_squadre".
alter table giocatori drop column if exists id_squadra;
