-- ============================================================
-- Ricrea da zero, su un progetto Supabase NUOVO e vuoto, tutte le
-- tabelle del sito U.S. Rio A.S.D. così come sono oggi, con tutti i
-- collegamenti tra loro.
--
-- Perché serve questo file: il progetto Supabase attuale è nato
-- pian piano, con tanti piccoli script diversi (quelli nella cartella
-- "sql/") eseguiti uno alla volta nel tempo. Rifarli uno per uno nello
-- stesso ordine su un progetto nuovo sarebbe complicato e rischioso
-- (alcuni di quegli script correggono o annullano quello che avevano
-- fatto script precedenti). Questo file, invece, crea DIRETTAMENTE il
-- risultato finale: le stesse 8 tabelle, con le stesse colonne, che ha
-- oggi il progetto attuale.
--
-- Cosa NON fa questo file: non copia i dati (i giocatori, i
-- certificati) dal vecchio progetto. Nel vecchio progetto ci sono solo
-- dati di prova (giocatori finti, email di esempio), quindi non serve
-- portarli sul progetto nuovo: potrai aggiungere le squadre e i
-- giocatori veri direttamente dal sito, una volta collegato al nuovo
-- progetto. Aggiunge però automaticamente una squadra di partenza
-- ("Prima Squadra", rinominabile dal sito) e la riga delle
-- Impostazioni del sito, così il sito funziona subito.
--
-- Come usarlo:
-- 1. Apri il NUOVO progetto su supabase.com (quello con l'email dello
--    stage)
-- 2. Nel menu a sinistra vai su "SQL Editor"
-- 3. Clicca "New query"
-- 4. Incolla tutto questo file
-- 5. Clicca "Run" (o il pulsante Play)
--
-- Dopo aver eseguito questo file, restano da fare solo due cose,
-- fuori da Supabase:
-- 1. Nel file "server/.env" del progetto, aggiorna SUPABASE_URL e
--    SUPABASE_KEY con quelli del progetto NUOVO (li trovi su
--    supabase.com -> il progetto nuovo -> Settings -> API).
-- 2. Avvia il server (npm start): lo spazio per le foto dei
--    certificati ("Storage bucket") si crea da solo in automatico al
--    primo avvio, non serve fare nulla a mano su Supabase per quello.
-- ============================================================

begin;

-- 1) Dati anagrafici condivisi tra giocatori e responsabili.
--
-- NOTA sull'email: qui NON la rendiamo "unique" (a differenza del
-- progetto originale) perché, su richiesta, i dati di esempio danno a
-- tutte le persone la stessa email (stage02@engimedia.it). ATTENZIONE:
-- questo toglie anche una protezione che il sito usa quando aggiungete
-- un giocatore vero dalla pagina "Nuovo giocatore" — normalmente, se
-- provi a inserire due volte la stessa email, il sito lo blocca con un
-- errore ("Esiste già una persona con questa email"); senza questa
-- regola, quel controllo non funziona più e potreste ritrovarvi con
-- due persone diverse che hanno per sbaglio la stessa email.
create table if not exists persona (
  id bigint generated by default as identity primary key,
  nome text not null,
  cognome text not null,
  email text not null,
  data_nascita date
);

-- Se la tabella esisteva già (per esempio da un tentativo precedente)
-- con la regola dell'email unica, questa riga la toglie: senza,
-- "create table if not exists" da solo non l'avrebbe tolta.
alter table persona drop constraint if exists persona_email_key;

-- 2) Categorie della società: una sola squadra di partenza (puoi
--    rinominarla o aggiungerne altre in qualsiasi momento dal sito).
create table if not exists squadre (
  id bigint generated by default as identity primary key,
  nome text not null unique
);

insert into squadre (nome) values
  ('Prima Squadra')
on conflict (nome) do nothing;

-- 3) Responsabili (allenatori/staff): ogni responsabile è legato alla
--    propria persona e alla squadra che allena.
create table if not exists responsabili (
  id bigint generated by default as identity primary key,
  id_persona bigint not null references persona(id),
  id_squadra bigint not null references squadre(id)
);

-- 4) Giocatori: legati alla propria persona, al proprio responsabile
--    (facoltativo) e alla propria squadra (facoltativa: resta vuota
--    solo se la squadra a cui apparteneva è stata eliminata).
create table if not exists giocatori (
  id bigint generated by default as identity primary key,
  id_persona bigint not null references persona(id),
  id_responsabile bigint references responsabili(id),
  id_squadra bigint references squadre(id) on delete set null,
  ruolo text not null,
  piede_preferito text not null,

  -- Un giocatore "eliminato" dal sito non viene mai cancellato per
  -- davvero dal database, solo segnato come archiviato (per non
  -- perdere la sua storia di certificati).
  archiviato boolean not null default false,

  -- Data e ora dell'ultimo "ripristino" di un giocatore archiviato
  -- (vuoto se non è mai stato archiviato/ripristinato): i certificati
  -- caricati prima di questa data restano per sempre nell'archivio.
  certificati_azzerati_al timestamptz
);

-- 5) Certificati medici: un giocatore può avere più righe (quello
--    "attuale", già approvato, e uno "nuovo" appena caricato in
--    attesa di approvazione).
create table if not exists certificati_medici (
  id bigint generated by default as identity primary key,
  id_giocatore bigint not null references giocatori(id) on delete cascade,

  -- 'attesa'    = caricato, in attesa di approvazione
  -- 'approvato' = approvato dal responsabile
  -- 'scartato'  = era stato approvato, ma poi scartato dall'Admin (per
  --   esempio per errore): resta qui, con il motivo, invece di essere
  --   eliminato, per tenerne traccia nell'Archivio.
  stato text not null default 'attesa' check (stato in ('attesa', 'approvato', 'scartato')),

  -- percorso della foto dentro lo Storage di Supabase (non la foto
  -- vera e propria: quella resta nello Storage, qui teniamo solo
  -- "dove trovarla")
  foto_path text,

  data_rilascio date,
  data_scadenza date,
  nota text,

  -- Compilati solo se il certificato viene scartato dopo essere stato
  -- approvato (stato 'scartato'): il motivo scritto dall'Admin e
  -- quando è successo.
  motivo_scarto text,
  data_scarto timestamptz,

  data_caricamento timestamptz not null default now(),
  data_approvazione timestamptz
);

-- 6) Segnalazioni: certificati caricati scrivendo un nome che non
--    corrisponde a nessun giocatore del sito.
create table if not exists segnalazioni_certificati (
  id bigint generated by default as identity primary key,

  nome text not null,
  cognome text not null,
  data_rilascio date not null,
  nota text,

  -- percorso della foto nello Storage di Supabase (stesso "bucket" dei
  -- certificati veri, cartella "segnalazioni/")
  foto_path text not null,

  -- 'in_attesa': ancora da gestire.
  -- 'collegata': collegata a un giocatore vero (è diventata un
  --   certificato vero e proprio, vedi id_certificato_creato).
  -- 'scartata': non corrispondeva a nessuno.
  stato text not null default 'in_attesa' check (stato in ('in_attesa', 'collegata', 'scartata')),

  id_giocatore_collegato bigint references giocatori(id),
  id_certificato_creato bigint references certificati_medici(id),

  creato_il timestamptz not null default now(),
  gestito_il timestamptz
);

-- 7) Storico delle email mandate ai giocatori (approvazione, scarto,
--    in scadenza, scaduto, collegamento di una segnalazione). Il
--    collegamento al certificato è facoltativo: se il certificato
--    viene poi eliminato (scarto), la notifica resta comunque nello
--    storico.
create table if not exists notifiche_inviate (
  id bigint generated by default as identity primary key,
  id_certificato bigint references certificati_medici(id) on delete set null,
  tipo text,
  nome_giocatore text,
  cognome_giocatore text,
  data_invio timestamptz not null default now(),
  destinatario text
);

-- 8) Impostazioni del sito: una riga sola (id = 1), con il nome della
--    società e i dati della pagina Contatti.
create table if not exists impostazioni_sito (
  id integer primary key default 1,
  nome_sito text not null default 'U.S. Rio A.S.D.',
  indirizzo text,
  telefono text,
  email text,
  campo_gioco text,
  constraint impostazioni_sito_una_sola_riga check (id = 1)
);

insert into impostazioni_sito (id, nome_sito)
values (1, 'U.S. Rio A.S.D.')
on conflict (id) do nothing;

commit;
